root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/bin/web ./cmd/web"
  entrypoint = ["./tmp/bin/web", "-addr", ":4000"]
  delay = 200
  exclude_dir = ["tmp", "vendor", ".git", "plans"]
  include_ext = ["go", "html", "css", "js", "svg"]
  stop_on_error = true

[log]
  time = true

[screen]
  clear_on_rebuild = true
