package main

type homePageData struct {
	Projects []projectPageData
}

type projectFeatureGroup struct {
	Title string
	Items []string
}

type projectShowcaseImage struct {
	Path string
	Alt  string
}

type projectPageData struct {
	ProjectID       int
	ProjectTitle    string
	Label           string
	CardSummary     string
	Stack           string
	ImagePath       string
	ImageAlt        string
	ShowcaseImages  []projectShowcaseImage
	PageSummary     string
	Intro           []string
	FeatureGroups   []projectFeatureGroup
	GenerateCommand string
	RunCommand      string
	RepoURL         string
	Placeholder     bool
}

var portfolioProjects = []projectPageData{
	{
		ProjectID:    1,
		ProjectTitle: "IncLens",
		Label:        "tool://inclens",
		CardSummary:  "A terminal UI for exploring C++ include relationships from a preprocessed .ii file, with both tree and flamegraph views.",
		Stack:        "stack: Go / Bubble Tea / C++ include analysis",
		ImagePath:    "/static/img/inclens-topdown.gif",
		ImageAlt:     "IncLens top-down tree view demo",
		ShowcaseImages: []projectShowcaseImage{
			{
				Path: "/static/img/inclens-topdown.gif",
				Alt:  "IncLens top-down tree view demo",
			},
			{
				Path: "/static/img/inclens-flamegraph.gif",
				Alt:  "IncLens flamegraph view demo",
			},
		},
		PageSummary: "A terminal UI for exploring C++ include relationships from a preprocessed .ii file, with both a navigable tree view and a flamegraph view.",
		Intro: []string{
			"IncLens takes a preprocessed .ii file generated by g++ and turns it into an interactive view of the include hierarchy.",
			"It is built for understanding dependency structure, spotting heavy includes, and getting a quicker feel for compile-time cost directly from the terminal.",
		},
		FeatureGroups: []projectFeatureGroup{
			{
				Title: "Top-down tree view",
				Items: []string{
					"Navigate the include hierarchy as a tree.",
					"Expand and collapse nodes while moving through the structure.",
					"Search for includes and jump through matches.",
					"Sort files by file bytes, total bytes, file LOC, or total LOC.",
				},
			},
			{
				Title: "Flamegraph view",
				Items: []string{
					"Visualize includes proportionally by total lines of code.",
					"Move through the graph with the keyboard.",
					"Zoom in with Enter and back out with Esc.",
					"Inspect the current file name and LOC in the info panel.",
				},
			},
		},
		GenerateCommand: "g++ -E -o example.ii example.cpp",
		RunCommand:      "./inclensapp -file example.ii",
		RepoURL:         "https://github.com/gkonto/IncLens",
	},
	{
		ProjectID:    2,
		ProjectTitle: "Project 02",
		Label:        "project://coming-soon",
		CardSummary:  "A placeholder slot for the next tutorial, application, or review I want to add here.",
		Stack:        "stack: tbd",
		ImagePath:    "/static/img/project-placeholder.svg",
		ImageAlt:     "Placeholder preview for the next project",
		PageSummary:  "This page is still empty for now.",
		Placeholder:  true,
	},
}

func getProjectByID(id int) (projectPageData, bool) {
	for _, project := range portfolioProjects {
		if project.ProjectID == id {
			return project, true
		}
	}

	return projectPageData{}, false
}
